### ISSUE TITLE
Login issue on linux AppImage

### ISSUE THREAD

**Issue by ifedapoolarewaju** [ifedapoolarewaju/igdm#12]
On linux, when trying to login, the following error occurs:

A JavaScript error occurred in the main process

Uncaught Exception:
Error: EROFS: read-only file system, unlink '/tmp/.mount_uABPtV/usr/bin/resources/app/cookies/.keep'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:1099:18)
    at files.forEach (/tmp/.mount_uABPtV/usr/bin/resources/app/igdm.js:29:8)
    at Array.forEach (native)
    at Object.exports.login (/tmp/.mount_uABPtV/usr/bin/resources/app/igdm.js:28:9)
    at EventEmitter.electron.ipcMain.on (/tmp/.mount_uABPtV/usr/bin/resources/app/main.js:106:8)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/tmp/.mount_uABPtV/usr/bin/resources/electron.asar/browser/api/web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

There's a similar issue [here](https://github.com/electron-userland/electron-builder/issues/830).

Maybe we shouldn't store the session file for linux users or there should be options to set a path to where session data should be stored.

**Comment by ifedapoolarewaju** [comment]
fixed [here](https://github.com/ifedapoolarewaju/igdm/releases/tag/v2.0.2)
