### ISSUE TITLE
Installation Problem | module js:545

### ISSUE THREAD

**Issue by beyef3ndi** [ifedapoolarewaju/igdm#414]
Platform : Linux/Ubuntu Based
CPU : Amd64
My idea : I guess trouble with electron.
Version : Latest v2.5.0
Error Output : 
```
module.js:545
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_IGdm-2SvHzl3/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3


```

**Comment by MohamedNourTN** [comment]
Also Here ..! 
OS: Debian 9

**Comment by Maccer1** [comment]
Related #427
