### ISSUE TITLE
Error: module.js:545 on Debian

### ISSUE THREAD

**Issue by StevensDotB** [ifedapoolarewaju/igdm#467]
**When I run try to run it, I got this:**
module.js:545
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_IGdm-233t3UC/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3

**Comment by kabads** [comment]
I'm getting this issue also (on Arch Linux).

**Comment by StevensDotB** [comment]
I installed the latest version of electron, but it doesn't work yet.
