### ISSUE TITLE
unable to install the app

### ISSUE THREAD

**Issue by hbakhtiyor** [ifedapoolarewaju/igdm#507]
during installation of the [app](https://github.com/ifedapoolarewaju/igdm/releases/download/v2.5.1/IGdm-2.5.1-x86_64.AppImage), got the error

```
module.js:545
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_IGdm-28a8GhP/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
```

os: ubuntu 18.04.1 64bit

**Comment by arash-ash** [comment]
I got the same error.

**Comment by alberto-rodriguez-gonzalez** [comment]
same here
