### ISSUE TITLE
"Error: Cannot find module" on running the App

### ISSUE THREAD

**Issue by vivekteega** [ifedapoolarewaju/igdm#529]
I'm getting the following error when I run the app 

```
vivek@Teega:~/Downloads$ ./IGdm-2.5.1-x86_64.AppImage 
module.js:545
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_IGdm-2wh2Q76/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
```
Does anyone know whow to solve this?

**Comment by ifedapoolarewaju** [comment]
this issue is now fixed on version 2.5.2 please go to http://igdm.me and download the latest
