### ISSUE TITLE
Javascript error after latest update (2019/04/04)

### ISSUE THREAD

**Issue by mosaicthej** [ifedapoolarewaju/igdm#868]
![igdmerror](https://user-images.githubusercontent.com/45146801/55592398-8b90a700-56f5-11e9-9b36-8370735b6b14.JPG)
The error page showed up right after the latest update after the login, however, it doesn't seem to affect any text-based chat as all my messages went out and received. 

Also, the media upload went bad after the update, the .jpg format won't be uploaded.

respect

**Comment by normansaez** [comment]
same issue with 2.6.3

**Comment by sternj** [comment]
Same issue occurring on Linux Mint 19

**Comment by normansaez** [comment]
Could be related to this?

```
~/igdm/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/security-warnings.js:188 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security Policy set or a policy with "unsafe-eval" enabled. This exposes users of this app to unnecessary security risks.

For more information and help, consult https://electronjs.org/docs/tutorial/security.
This warning will not show up once the app is packaged.
warnAboutInsecureCSP @ ~/igdm/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/security-warnings.js:188
renderers.js:110 Uncaught TypeError: Cannot read property 'image_versions2' of undefined
    at Object.renderMessageAsRavenImage [as raven_media] (renderers.js:110)
    at renderMessage (renderers.js:24)
    at messages.forEach (renderers.js:265)
    at Array.forEach (<anonymous>)
    at renderOlderMessages (renderers.js:264)
    at EventEmitter.ipcRenderer.on (index.js:52)
    at emitTwo (events.js:126)
    at EventEmitter.emit (events.js:214)
renderMessageAsRavenImage @ renderers.js:110
renderMessage @ renderers.js:24
messages.forEach @ renderers.js:265
renderOlderMessages @ renderers.js:264
ipcRenderer.on @ index.js:52
emitTwo @ events.js:126
emit @ events.js:214
```

**Comment by blamot** [comment]
Same, macOS 10.14.4

**Comment by wilmeta** [comment]
Same issue with 2.6.3 on Windows 10.

**Comment by blamot** [comment]
Uncaught Exception:
TypeError: Cannot read property 'toString' of undefined
    at Account.parseParams (/Applications/IGdm.app/Contents/Resources/app.asar/node_modules/instagram-private-api/client/v1/account.js:20:57)
    at Account.InstagramResource.setParams (/Applications/IGdm.app/Contents/Resources/app.asar/node_modules/instagram-private-api/client/v1/resource.js:39:19)
    at Account.InstagramResource (/Applications/IGdm.app/Contents/Resources/app.asar/node_modules/instagram-private-api/client/v1/resource.js:13:10)
    at new Account (/Applications/IGdm.app/Contents/Resources/app.asar/node_modules/instagram-private-api/client/v1/account.js:9:14)
    at Thread.parseParams (/Applications/IGdm.app/Contents/Resources/app.asar/node_modules/instagram-private-api/client/v1/thread.js:61:20)
    at Thread.InstagramResource.setParams (/Applications/IGdm.app/Contents/Resources/app.asar/node_modules/instagram-private-api/client/v1/resource.js:39:19)
    at Thread.InstagramResource (/Applications/IGdm.app/Contents/Resources/app.asar/node_modules/instagram-private-api/client/v1/resource.js:13:10)
    at new Thread (/Applications/IGdm.app/Contents/Resources/app.asar/node_modules/instagram-private-api/client/v1/thread.js:9:14)
    at Object.exports.seen (/Applications/IGdm.app/Contents/Resources/app.asar/main/instagram.js:115:4)
    at EventEmitter.electron.ipcMain.on (/Applications/IGdm.app/Contents/Resources/app.asar/main/main.js:235:13)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7)
    at WebContents.<anonymous> (/Applications/IGdm.app/Contents/Resources/electron.asar/browser/api/web-contents.js:286:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

**Comment by miniatvre** [comment]
just hoping this gets fixed soon

**Comment by normansaez** [comment]
![img](https://user-images.githubusercontent.com/1967948/55644528-935f5280-57ac-11e9-932f-d9fc4212ea7a.png)

I post my error message. May the the title of the ticket is quite misleading

**Comment by kylerchin** [comment]
Same issue, Pop!_OS Ubuntu Linux 19.04 beta Latest version of IGDM. Plz fix!!!
