### ISSUE TITLE
Javascript Exception 

### ISSUE THREAD

**Issue by BraianVicente** [ifedapoolarewaju/igdm#870]
When I try to open a new conversation outside my recent conversations scope the following Javascript error appears.

![image](https://user-images.githubusercontent.com/9852789/55636745-e67bda00-5799-11e9-849e-8f1404804e94.png)

**Comment by downwithbgp** [comment]
Same thing on MacOS 10.14.5 Beta (18F96h)
```
Uncaught Exception:
TypeError: Cannot read property 'toString' of undefined
    at Account.parseParams (/Applications/IGdm.app/Contents/Resources/app.asar/node_modules/instagram-private-api/client/v1/account.js:20:57)
    at Account.InstagramResource.setParams (/Applications/IGdm.app/Contents/Resources/app.asar/node_modules/instagram-private-api/client/v1/resource.js:39:19)
    at Account.InstagramResource (/Applications/IGdm.app/Contents/Resources/app.asar/node_modules/instagram-private-api/client/v1/resource.js:13:10)
    at new Account (/Applications/IGdm.app/Contents/Resources/app.asar/node_modules/instagram-private-api/client/v1/account.js:9:14)
    at Thread.parseParams (/Applications/IGdm.app/Contents/Resources/app.asar/node_modules/instagram-private-api/client/v1/thread.js:61:20)
    at Thread.InstagramResource.setParams (/Applications/IGdm.app/Contents/Resources/app.asar/node_modules/instagram-private-api/client/v1/resource.js:39:19)
    at Thread.InstagramResource (/Applications/IGdm.app/Contents/Resources/app.asar/node_modules/instagram-private-api/client/v1/resource.js:13:10)
    at new Thread (/Applications/IGdm.app/Contents/Resources/app.asar/node_modules/instagram-private-api/client/v1/thread.js:9:14)
    at Object.exports.seen (/Applications/IGdm.app/Contents/Resources/app.asar/main/instagram.js:115:4)
    at EventEmitter.electron.ipcMain.on (/Applications/IGdm.app/Contents/Resources/app.asar/main/main.js:235:13)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7)
    at WebContents.<anonymous> (/Applications/IGdm.app/Contents/Resources/electron.asar/browser/api/web-contents.js:286:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
```

**Comment by Chimei1Cass** [comment]
Me too

**Comment by ifedapoolarewaju** [comment]
this is fixed now. please restart your app to install the latest update
