### ISSUE TITLE
Issue with the automatic update system

### ISSUE THREAD

**Issue by alexrecuenco** [ifedapoolarewaju/igdm#890]
Hello, 

I have looked through other issues, and I don't think I have seen this issue pop up yet.

Using this app, it spanned another window saying "Downloading application update..." and after a while (I guess it was downloading it,) It opped up a 3rd window with this exception log that I attach.

Note that after I closed that exception log, I guess it tried again, because I got the same exception (I think?) a few moments later, and after that, it just got stuck.

Note that my internet connection was fine, and that the main app-window seems to still be responsive while that is happening (I sent messages to some friends and received replies just fine) (I am using macOS Mojave in a macbook-pro, in case it is relevant, I homebrewed the app)

I hope you find this report useful, I really enjoy this app. Let me know if you need any extra information

```
Uncaught Exception:
TypeError: Cannot read property 'toString' of undefined
    at Account.parseParams (/Applications/IGdm.app/Contents/Resources/app.asar/node_modules/instagram-private-api/client/v1/account.js:20:57)
    at Account.InstagramResource.setParams (/Applications/IGdm.app/Contents/Resources/app.asar/node_modules/instagram-private-api/client/v1/resource.js:39:19)
    at Account.InstagramResource (/Applications/IGdm.app/Contents/Resources/app.asar/node_modules/instagram-private-api/client/v1/resource.js:13:10)
    at new Account (/Applications/IGdm.app/Contents/Resources/app.asar/node_modules/instagram-private-api/client/v1/account.js:9:14)
    at Thread.parseParams (/Applications/IGdm.app/Contents/Resources/app.asar/node_modules/instagram-private-api/client/v1/thread.js:61:20)
    at Thread.InstagramResource.setParams (/Applications/IGdm.app/Contents/Resources/app.asar/node_modules/instagram-private-api/client/v1/resource.js:39:19)
    at Thread.InstagramResource (/Applications/IGdm.app/Contents/Resources/app.asar/node_modules/instagram-private-api/client/v1/resource.js:13:10)
    at new Thread (/Applications/IGdm.app/Contents/Resources/app.asar/node_modules/instagram-private-api/client/v1/thread.js:9:14)
    at Object.exports.seen (/Applications/IGdm.app/Contents/Resources/app.asar/main/instagram.js:115:4)
    at EventEmitter.electron.ipcMain.on (/Applications/IGdm.app/Contents/Resources/app.asar/main/main.js:235:13)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7)
    at WebContents.<anonymous> (/Applications/IGdm.app/Contents/Resources/electron.asar/browser/api/web-contents.js:286:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
```

**Comment by ifedapoolarewaju** [comment]
@alexrecuenco this issue has been fixed for some time now. Please ensure you are running the latest version of IGdm and you shouldn't get the issue
